Lab Setup and Instruction for Case Studies in Machine Learning

In [2]:
import numpy as np

In [3]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array 1 array TYPE:', array1.shape)

array2 = np.array([[1, 2, 3], [4, 5, 6]])
print('array2 type:', type(array2))
print('array 2 array TYPE:', array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array 3 array TYPE:', array3.shape)

array1 type: <class 'numpy.ndarray'>
array 1 array TYPE: (3,)
array2 type: <class 'numpy.ndarray'>
array 2 array TYPE: (2, 3)
array3 type: <class 'numpy.ndarray'>
array 3 array TYPE: (1, 3)


In [4]:
print('array1: {:0} Dimension, array2: {:1} Dimension, array3: {:2} Dimension'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1 Dimension, array2: 2 Dimension, array3:  2 Dimension


In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [7]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(list2)
print(array2, array2.dtype)

[1, 2, 'test']
['1' '2' 'test'] <U21


In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [10]:
zero_array = np.zeros((3,4),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32 (3, 4)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [11]:
print(array1)
print(array1.shape)

[1 2 3]
(3,)


In [14]:
#array1.reshape(4,3)
#does not work

array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1)
print('array3 shape:', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [15]:
array1 = np.arange(start =1, stop = 10)
print('array1:', array1)

value = array1[2]
print('value:', value) 
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [16]:
print('Back:', array1[-1], ',Second Back:', array1[-2])

Back: 9 ,Second Back: 8


In [17]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [18]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [19]:
rand = np.random.RandomState(42)

x = rand.randint(100, size = 10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [20]:
[x[3],x[7],x[2]]

[np.int64(71), np.int64(86), np.int64(14)]

In [21]:
ind = [3,7,4]
x[ind]

array([71, 86, 60])

In [22]:
ind = np.array([[3,7],[4,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [23]:
X = np.arange(12).reshape(3,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
row = np.array([0,1,2])
col = np.array([2,1,3])
X[row,col]

array([ 2,  5, 11])

In [25]:
array1d = np.arange(start =1 , stop = 10)

array3 = array1d[array1d > 5]
print('array1d > 5 Boolean Indexing Result:', array3)

array1d > 5 Boolean Indexing Result: [6 7 8 9]


In [26]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [28]:
A = np.array([[1,2],[3,4]])
transpose_mat = np.transpose(A)

print('Inverse Matrix A:', transpose_mat)

Inverse Matrix A: [[1 3]
 [2 4]]
